<footer>
    <p><i class="fas fa-copyright"></i> 2017 ArchiTEC. Design by <strong>Adeelo .</strong></p>
</footer>

<!-- Charger le script js -->
<script src="../../assets/js/main.js" type="text/javascript"></script>
<script src="../../assets/js/mainAjax.js" type="text/javascript"></script>

<!-- Charger la bibliothèque de base de jQuery -->
<script type="text/javascript" src="../../assets/js/jquery-3.5.1.min.js"></script>

<!-- Charger le JS de Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

</script>

</body>
</html>
