<nav id="mySidenav" class="sidenav">
	<img src="../../assets/images/logos/logo.blanc.png" class="logo2" alt= "logo ArchiTEC">
  	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">FERMER</a>
  
	<div class="burger">
		<a href="../../src/frontOffice/index.php" class="home">HOME</a>
		<a href="../../src/frontOffice/bureau.php" class="bureau">BUREAU</a>
		<a href="../../src/frontOffice/projets.php">PROJETS</a>
		<a href="../../src/frontOffice/actualite.php">Actualités</a>
		<a href="../../src/frontOffice/contact.php">CONTACT</a>
		<div class="left"></div>
		<div class="right"></div>
		<div class="bottom"></div>
    </div>
    
	<div class="bottomLinks">
		<a href="../../src/frontOffice/postuler.php">recrutement</a> 
		<div class="reseaux">
			<a href="https://www.facebook.com/profile.php?id=100079413816296">facebook</a>
			<a href="https://www.instagram.com/architec004/">instagram</a>
			<a href="https://www.linkedin.com/in/archi-tec-33b780234/">linkedin</a>
		</div>
	</div>
</nav>

