<?php
    if (isset($valids) && count($valids) > 0) : ?>
        <div id="messageValidation">
            <div>
                <img src="../../assets/images/img_valids.errors/validation.png" alt="Validation" class="imgErrorAndValid"/>
            </div>
            <div>
                <ul>
                    <?php foreach($valids as $valid) : ?>
                        <li><?= $valid; ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>