<?php require_once('_header.phtml'); ?>

<main>
    <section class="presentation2">
        <div class="text">
            <h1><?= BUREAU ?></h1>
            <h2>S’ENGAGER AU SERVICE <br> DE L’INNOVATION</h2>
    
            <article>
                <p>Fondé en 2017, ArchiTEC est dirigé par une équipe d’architectes et de graphistes passionnés et expérimentés rompus à toutes les techniques de création visuelle : croquis, modélisation 3D, photoréalisme, vidéos, maquettes, réalité virtuelle. S’attachant à proposer des idées innovantes, parfois décalées mais toujours pérennes, l’équipe s’appuie sur des profils divers et complémentaires : rêveurs et pragmatiques, créatifs et techniciens.
                </p>
                <p>Chaque projet d’architecture, de réhabilitation, d’architecture intérieure ou de design fait l’objet d’un soin tout particulier, quelle que soit sa taille, son envergure, sa spécificité, sa destination. Nous travaillons toujours en équipe, de façon à mutualiser nos compétences et nos idées, et à maximiser la qualité et la cohérence de nos réponses.
                    Notre credo : la personnalisation de votre projet, dans une démarche inspirée du design global.
                </p>
            </article>
            <button onclick="bottomFunction()" id="myBtnBottom2" title="Go to bottom">
                <img src="../../assets/images/img_picto/arrowBottom.jpg" class='arrowBottom' alt="aller en bas de la page">    
            </button>
        </div>
    </section>

    <section class="containerBureau">
        <h2 id="equipe">l'équipe</h2>
        <img src="../../assets/images/img_bureau/equipe.jpg" alt="image de l'équipe d'architectes">
        <div class="texte">
            <span>racontez-nous votre histoire, nous nous occupons de la mettre en scène !</span>
            <div class="trait1"></div>
        </div>
        
        <article class="article1">
            <h3>une démarche inspirée du design global</h3>
            <p>Pour qu’un projet gagne en cohérence, en authenticité et en unicité, nous cherchons à articuler deux ingrédients majeurs : l’identité du lieu et la personnalité de ses occupants. Ce sont eux qui constituent la trame de votre histoire et de la vision globale du projet que nous construisons pour vous. Ensuite, parce que sa réussite repose sur l’attention prêtée à chaque détail, nous élaborons une scénographie précise de votre espace, qui se traduit par le choix des couleurs, des formes, des matériaux, de l’agencement, de la décoration, du mobilier, des objets, accessoires, luminaires, jusqu’à la communication visuelle, la typographie… Tous ces éléments donnent du sens à votre projet et bâtissent son identité globale.</p>
            <p>Exemple : Vous avez un restaurant ? Pour optimiser l’image que vous souhaitez renvoyer à vos clients, nous vous proposons un accompagnement sur mesure et une harmonisation de tous les éléments qui composent votre espace, de la conception du lieu jusqu’à la </p>
        </article>
        
        <section class="activities">
            <div class="columnLeft">Aménagement sur-mesure by ArchiTEC</div>
            <h2>Prestations & engagements <h2>
            <h3>ARCHITECTURE PRO & PARTICULIER<h3> 
            <div class="trait1"></div>
            
            <article>
                <p><span class="purple">Nos activités </span>couvrent un large spectre : architecture, rénovation, réhabilitation, architecture d’intérieur, aménagement, agencement d’espaces professionnels (boutiques, vitrines, hôtels, restaurants…), design d’espace (agencement de scènes, d’événements, de lieux éphémères…), design de mobilier, communication visuelle (commerces, restaurants…), décoration, etc.</p>
                
                <p><span class="purple">Nos préstations</span> : conseil, études, conception, visualisation (3D, maquettes, croquis, réalité virtuelle, etc.), création graphique, maîtrise d’œuvre, déclarations préalables (permis de construire, ouverture d’ERP…), etc.</p>
                
                <p><span class="purple">Nos partenaires</span> : dès la conception du projet et jusqu’à sa finalisation, nous travaillons en étroite collaboration avec des sociétés locales (entreprises générales, artisans) dont l’expertise de chantier est reconnue, ce qui nous permet de répondre au mieux aux contraintes techniques et budgétaires.</p>
                
                <p><span class="purple">Nos engagements</span> :  - le dialogue constant avec vous, parce que c’est la condition préalable, le vecteur de confiance et le fil conducteur de tous nos projets - le respect du cahier des charges, du planning et du budget, mais aussi des normes et des règles qui régissent notre profession - le souci du détail et sa mise en œuvre, parce que c’est dans cette attention que réside la réussite d’un projet et sa pérennité .</p>
            </article>
            
            <div class="plus3">
                <a href="../../src/frontOffice/projets.php"><img src="../../assets/images/img_picto/plus.jpg" alt="plus de projets">Projets</a> 
                <a href="https://www.architectes.org/"><img src="../../assets/images/logos/logo-ordre-archi.jpg" class="imgOrdre" alt="logo ordre des architectes"></a>
                <div class="ordre">
                    <a href="../../src/frontOffice/contact.php" class="aPropos">contact</a>
                </div>
            </div>
        </section>
        
        <aside class="aside">
            <h2>Recherche et <br>innovation</h2>
            <div class="ecologie">
                <img src="../../assets/images/img_bureau/ecologie.jpg" alt="image bureau">
                <img src="../../assets/images/img_bureau/archiTEC.jpg" alt="image bureau">
            </div>
            
            <article>
                <h3>une logique d'amélioration continue</h3>
                <p>En parallèle de nos réalisations, nous cherchons sans cesse à nous renouveler, dans nos pratiques, dans notre dynamique d’accompagnement, dans la diversité des techniques utilisées. Nous avons ainsi adopté la méthode BIM (Building Interactive Management), un processus de travail qui modélise et réunit toutes les données d’un projet en un fichier unique, ce qui garantit la bonne gestion de nos projets de construction.
                </p>
            </article>
        </aside>
     
        <button onclick="topFunction()" id="myBtn" title="Go to top"><img src="../../assets/images/img_picto/arrowTop.jpg" alt="image go to Top"></button>
    </section>
</main>

<?php require_once('_footer.phtml'); ?>