<?php require_once('_header.phtml'); ?>

<main class="containerProjet">
    
    <?php if(!isset($_GET['id']) && $_GET['id'] <= 0 && $Projet['img_name'] == ''): ?>
        <p>Désolé, aucun Projet correspond à votre recherche.</p>
    <?php else: ?>
    
        <img src="../../assets/images/image_principale/<?= $Projet['img_name'] ?>" class="imageProjet" alt="image principale du projet">
    
        <article class="descriptionProjet">
            <h1><?= htmlspecialchars($Projet['pro_title']) ?></h1>
            <p><?= htmlspecialchars($Projet['pro_description']) ?></p>
            <p>Catégorie : <?= htmlspecialchars($Projet['cat_title']) ?></p>
            <p>Maitre d'ouvrage : <?= htmlspecialchars($Projet['pro_owner']) ?></p>
            <p>Réalisation : <?= htmlspecialchars($Projet['pro_date']) ?></p>
        </article>
                    
        <article class="descriptionCategorie">
            <h2><?= htmlspecialchars($Projet['cat_title']) ?></h2>
            <p><?= htmlspecialchars($Projet['cat_description']) ?></p>
        </article>
    <?php endif; ?>
                    
    <?php if(!isset($photo1) && !isset($photo2) && !isset($photo3)) : ?>
        <p>Désolé, Nous n'avons pas encore rajouter des photos démonstratives de ce projet.</p>
        
    <?php else: ?>
        <!-- Le Slideshow des images projet en bootstrap 5-->
        <div id="demo" class="carousel slide" data-bs-ride="carousel">
            <!-- Indicators/dots -->
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
                <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
            </div>
                
            <!-- The slideshow/carousel -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="../../uploads/img_projets/<?= $photo1['photo_name'] ?>" alt="photo projet" class="d-block">
                    <div class="carousel-caption">
                        <h3>ArchiTEC</h3>
                        <p>La solution idéale</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="../../uploads/img_projets/<?= $photo2['photo_name'] ?>" alt="photo projet" class="d-block">
                    <div class="carousel-caption">
                        <h3>ArchiTEC</h3>
                        <p>La solution idéale</p>
                    </div> 
                </div>
                <div class="carousel-item">
                    <img src="../../uploads/img_projets/<?= $photo3['photo_name'] ?>" alt="photo projet" class="d-block">
                    <div class="carousel-caption">
                        <h3>ArchiTEC</h3>
                        <p>La solution idéale</p>
                    </div>  
                </div>
            </div>
      
            <!-- Left and right controls/icons -->
            <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
                <span class="carousel-control-next-icon"></span>
            </button>
        </div>

    <?php endif; ?> 
        
    <button  id="myBtn1" title="changer de page"><img src="../../assets/images/img_picto/cursorClose.jpg"></button>
</main>

<?php require_once('_footer.phtml'); ?>
