<?php

    if (isset($errors) && count($errors) > 0) : ?>
        <div id="messagesErrors">
            <div>
                <img src="../../assets/images/img_valids.errors/warning.gif" alt="Triangle warning" class="imgErrorAndValid"/>
            </div>
            
            <div>
                <ul>
                    <?php foreach($errors as $error) : ?>
                        <li><?= $error; ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    <?php endif; ?>