<?php

if(isset($_SESSION['arc']) && $_SESSION['arc']['role'] = "ADMIN"): ?>
    <h1>
        <img src="../../assets/images/avatar_admins/<?= $_SESSION['arc']['avatar']; ?>" class="img_admin "alt="picture administrateur"><?= TITLE_BACK ?>
    </h1>
    
<?php else: ?>
    <img src="../../assets/images/avatar_admins/noAvatar.JPG" class="img_admin "alt="picture administrateur par défaut">
    
<?php endif; ?>




