<?php require_once('_headerBack.phtml'); ?>

<main class="adminContainer">
   
    <?php require_once('_titleAvatar.phtml'); ?>
    
    <h2>Gestion des Projets :</h2>
    <a class="add1" href="../../src/backOffice/adminNewAndUpdate.php"><i class="fas fa-plus-circle"></i>Ajouter un Administrateur</a>
    <a class="add2" href="../../src/backOffice/projetNewAndUpdate.php"><i class="fas fa-plus-circle"></i> Ajouter un Projet</a>
    
    <?php if(isset($_SESSION['message'])) : ?>
        <div class="MessageSession">
            <img src="../../assets/images/img_valids.errors/warning.gif" alt="Triangle warning" class="imgErrorAndValid"/>
            <ul>
                <li><?= $_SESSION['message'] ?></li>
            </ul>
            <img src="../../assets/images/img_valids.errors/warning.gif" alt="Triangle warning" class="imgErrorAndValid"/>
        </div>
        <?php unset($_SESSION['message']) ?>
        
    <?php endif; ?>

    <table class="projetTable">
    	<thead>
        	<tr>
                <th>Titre</th>
                <th>Ajout photos</th>
                <th>Catégorie</th>
                <th>Date</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
    	</thead>
    	<tbody>
            <?php foreach($rowprojets as $rowprojet): ?>
                <tr>
                    <td><?= htmlspecialchars($rowprojet['pro_title']) ?></td>
                    <td class="center"><a href="../../src/backOffice/photoNew.php?id=<?= htmlspecialchars($rowprojet['pro_id']) ?>"><i class="fas fa-plus-circle"></i></a>
                    </td>
                    <td><?= htmlspecialchars($rowprojet['cat_title']) ?></td>
                    <td><?= htmlspecialchars($rowprojet['pro_date']) ?></td>
                    <td class="center"><a href="../../src/backOffice/projetNewAndUpdate.php?id=<?= htmlspecialchars($rowprojet['pro_id']) ?>"><i class="fas fa-wrench"></i></a>
                    </td>
                    <td class="center"><a href="../../src/backOffice/projetDelete.php?id=<?= htmlspecialchars($rowprojet['pro_id']) ?>" ... onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce Projet ?');" ><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</main>

<?php require_once('_footerBack.phtml'); ?>