<?php require_once('_headerBack.phtml'); ?>

<main class="adminContainer">
        
    <?php require_once('_titleAvatar.phtml'); ?>
    <h2>Gestion des Catégories :</h2>
    <a class="add1" href="../../src/backOffice/categorieNewAndUpdate.php"><i class="fas fa-plus-circle"></i>Ajouter une Catégories</a>

    <table class="categoryTable">
        <thead>
            <tr>
                <th>Titre</th>
                <th>Description</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($rowCategories as $rowCategorie): ?>
                <tr>
                    <td><?= htmlspecialchars($rowCategorie['cat_title']) ?></td>
                    <td><?= substr(nl2br(htmlspecialchars($rowCategorie['cat_description'])), 0, 60) ?>...</td>
                    <td class="center"><a href="../../src/backOffice/categorieNewAndUpdate.php?id=<?= htmlspecialchars($rowCategorie['cat_id']) ?>"><i class="fas fa-wrench"></i></a>
                    </td>
                    <td class="center"><a href="../../src/backOffice/categorieDelete.php?id=<?= htmlspecialchars($rowCategorie['cat_id']) ?>" ... onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette catégorie ?');" ><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</main>

<?php require_once('_footerBack.phtml'); ?>