<?php require_once('_headerBack.phtml'); ?>

<main class="adminContainer">
        
    <?php require_once('_titleAvatar.phtml'); ?>
    <h2>Gestion des Postes :</h2>
    <a class="add1" href="../../src/backOffice/posteNewAndUpdate.php"><i class="fas fa-plus-circle"></i>Ajouter un poste</a>

    <table class="posteTable">
        <thead>
            <tr>
                <th>Titre du poste</th>
                <th>Catégorie</th>
                <th>Contrat</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($rowpostes as $rowposte): ?>
                <tr>
                    <td><?= htmlspecialchars($rowposte['post_name']) ?></td>
                    <td><?= htmlspecialchars($rowposte['cat_title']) ?></td>
                    <td><?= htmlspecialchars($rowposte['post_contrat']) ?></td>
                    <td class="center"><a href="../../src/backOffice/posteNewAndUpdate.php?id=<?= htmlspecialchars($rowposte['post_id']) ?>"><i class="fas fa-wrench"></i></a></td>
                    <td class="center"><a href="../../src/backOffice/posteDelete.php?id=<?= htmlspecialchars($rowposte['post_id']) ?>" ... onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce Poste ?');" ><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
</main>

<?php require_once('_footerBack.phtml'); ?>