<?php require_once('_headerBack.phtml'); ?>

<main class="addAndUpdate">
    
    <?php if(array_key_exists('id', $_GET) && $_GET['id'] >= 1) : ?>
        <h1>Bonjour, Modifier votre projet !</h1>
        <h3>Modification Projet :</h3>
        <?php require_once('_validsBack.phtml'); ?>
        <?php require_once('_errorsBack.phtml'); ?>
        <form method="POST" enctype="multipart/form-data" action="../../src/backOffice/projetNewAndUpdate.php?id=<?= htmlspecialchars($_GET['id']); ?>">
        
    <?php else: ?>
    
        <h1>Bonjour Ajoutez nouveau projet !</h1>
        <h3>Ajout d'un Projet :</h3>
        <?php require_once('_validsBack.phtml'); ?>
        <?php require_once('_errorsBack.phtml'); ?>
        <form action="../../src/backOffice/projetNewAndUpdate.php" enctype="multipart/form-data" method="POST">
  
    <?php endif; ?>
    
        <label for="categorie">Catégorie du Projet :</label>
            <select name="categorie" class="categorie">
                <option value="error">CATEGORIE :</option>
                <?php foreach($categories as $cat): ?>
                <option value="<?= htmlspecialchars($cat['cat_id']) ?>"
                    <?php if($addProjet['addCategory'] == $cat['cat_id']) :?>selected <?php endif; ?>>
                    <?= htmlspecialchars($cat['cat_title']) ?>
                </option>
                <?php endforeach; ?>
            </select><br>
  
        <label for="title">Titre :</label>
            <input type="text" name="title" value="<?= htmlspecialchars($addProjet['addTitle'])?>">

        <label for="description">Description :</label>
            <textarea id="description" name="description" rows="5" cols="33"><?= htmlspecialchars($addProjet['addDescription']) ?></textarea>
        
        <label for="date_start">Date de réalisation :</label>
            <input type="date" id="date_start" name="date_start" value="<?= htmlspecialchars($addProjet['addDate'])?>">
        
        <label for="owner">Maitre d'ouvrage :</label>
            <input type="text" name="owner" value="<?= htmlspecialchars($addProjet['addOwner'])?>">
        
        <fieldset>
            <label for="img_name">Image principale : </label>
                <input type="file" name="img_name">
        </fieldset>

        <?php if(array_key_exists('id', $_GET) && $_GET['id'] >= 1) : ?>
        <img src="../../assets/images/image_principale/<?= htmlspecialchars($addProjet['addImage'])?>" class="img_exist" alt="image exist">
            <input type="submit" value="Modifier">
        <?php else: ?>
            <input type="submit" value="Ajouter">
        <?php endif; ?>
    </form> 
    
</main>

<!-- Charger flatpickr pour limiter la date -->  
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>   
    flatpickr("#date_start", {
        maxDate: "today"
    });
</script>

<?php require_once('_footerBack.phtml'); ?>
    
    
    
    
    
    
    

	