<?php require_once('_headerBack.phtml'); ?>

<main class="adminContainer">
    <?php require_once('_titleAvatar.phtml'); ?>
    <h2>Gestion des Rendez-vous :</h2>
    <a class="add1" href="../../src/backOffice/rdvNewAndUpdate.php"><i class="fas fa-plus-circle"></i>Ajouter un Rendez-vous</a>

    <table class="rdvTable">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Email</th>
                <th>Date et Heure</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($rowAppointments as $rowAppointment): ?>
                <tr>
                    <td><?= htmlspecialchars($rowAppointment['app_name']) ?></td>
                    <td><?= htmlspecialchars($rowAppointment['app_lastname']) ?></td>
                    <td><?= htmlspecialchars($rowAppointment['app_mail']) ?></td>
                    <td><?= htmlspecialchars($rowAppointment['app_date']) ?></td>
                    <td class="center"><a href="../../src/backOffice/rdvNewAndUpdate.php?id=<?= htmlspecialchars($rowAppointment['app_id']) ?>"><i class="fas fa-wrench"></i></a>
                    </td>
                    <td class="center"><a href="../../src/backOffice/rdvDelete.php?id=<?= htmlspecialchars($rowAppointment['app_id']) ?>" ... onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce Rendez-vous ?');" ><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</main>

<?php require_once('_footerBack.phtml'); ?>